%% Bus structure for constants


busCell = { ...
        { ...
            'Bus_state', ...
            {{'r_i',3,'double', -1,'real','Sample', 'Fixed', [], [], 'km','Position in ECI' }; ...
            {'v_i',3,'double', -1,'real','Sample', 'Fixed', [], [], 'km/s','Velocity in ECI' }; ...
            {'a_i',3,'double', -1,'real','Sample', 'Fixed', [], [], 'km/s^2','Acceleration in ECI' }; ...
            {'q_b_i_b',4,'double', -1,'real','Sample', 'Fixed', [], [], '','Quaternion placeholder for now' }; ...
            }, ...
        };
        { ...
            'Bus_roe', ...
            {{'adot',1,'double', -1,'real','Sample', 'Fixed', [], [], '','' }; ...
            {'da',1,'double', -1,'real','Sample', 'Fixed', [], [], '','' }; ...
            {'dL',1,'double', -1,'real','Sample', 'Fixed', [], [], '','' }; ...
            {'dex',1,'double', -1,'real','Sample', 'Fixed', [], [], '','' }; ...
            {'dey',1,'double', -1,'real','Sample', 'Fixed', [], [], '','' }; ...
            {'dix',1,'double', -1,'real','Sample', 'Fixed', [], [], '','' }; ...
            {'diy',1,'double', -1,'real','Sample', 'Fixed', [], [], '','' }; ...
            }, ...
        };
};

Simulink.Bus.cellToObject(busCell);