%% Bus structure for constants


busCell = { ...
        { ...
            'Bus_state', ...
            {{'r_i',3,'double', -1,'real','Sample', 'Fixed', [], [], 'km','Position in ECI' }; ...
            {'v_i',3,'double', -1,'real','Sample', 'Fixed', [], [], 'km/s','Velocity in ECI' }; ...
            {'q_b_i_b',4,'double', -1,'real','Sample', 'Fixed', [], [], '','Quaternion placeholder for now' }; ...
            }, ...
        };
};

Simulink.Bus.cellToObject(busCell);