%% Bus structure for constants


busCell = { ...
        { ...
            'Bus_CON', ...
            {{'mu',1,'double', -1,'real','Sample', 'Fixed', [], [], 'km^3/s^2','Gravitational Parameter for the Earth' }; ...
            {'gravityFlag',1,'double', -1,'real','Sample', 'Fixed', [], [], '','Gravity flag' }; ...
            {'Re',1,'double', -1,'real','Sample', 'Fixed', [], [], 'km','Radius of the Earth' }; ...
            {'J2',1,'double', -1,'real','Sample', 'Fixed', [], [], 'km^5/s^2','J2 Value' }; ...
            }, ...
        };
};

Simulink.Bus.cellToObject(busCell);