%% Bus structure for constants


busCell = { ...
        { ...
            'Bus_sat', ...
            {{'ic',1,'Bus_state', -1,'real','Sample', 'Fixed', [], [], '','' }; ...
            {'DynFlag',1,'double', -1,'real','Sample', 'Fixed', [], [], '','' }; ...
            {'B',1,'double', -1,'real','Sample', 'Fixed', [], [], 'm^2/kg','Ballistic Coefficient' }; ...
            {'Cd',1,'double', -1,'real','Sample', 'Fixed', [], [], '','Drag Coefficient' }; ...
            
            }, ...
        };
};

Simulink.Bus.cellToObject(busCell);