%% Bus structure for constants


busCell = { ...
        { ...
            'Bus_CON', ...
            {{'mu',1,'double', -1,'real','Sample', 'Fixed', [], [], 'km^3/s^2','Gravitational Parameter for the Earth' }; ...
            {'gravityFlag',1,'double', -1,'real','Sample', 'Fixed', [], [], '','Gravity flag' }; ...
            {'Re',1,'double', -1,'real','Sample', 'Fixed', [], [], 'km','Radius of the Earth' }; ...
            {'J2',1,'double', -1,'real','Sample', 'Fixed', [], [], 'km^5/s^2','J2 Value' }; ...
            {'dragFlag',1,'double', -1,'real','Sample', 'Fixed', [], [], '','Drag flag' }; ...
            {'density',1,'Bus_CON_density', -1,'real','Sample', 'Fixed', [], [], '','Density Bus' }; ...
            {'dt',1,'double', -1,'real','Sample', 'Fixed', [], [], 's','Time step for sim' }; ...
            {'computer_dt',1,'double', -1,'real','Sample', 'Fixed', [], [], 's','Time step for computer' }; ...
            {'SampleTime',1,'double', -1,'real','Sample', 'Fixed', [], [], 's','Time step for Sampling' }; ...
            {'guidFlag',1,'double', -1,'real','Sample', 'Fixed', [], [], '','' }; ...
            {'lambda',1,'double', -1,'real','Sample', 'Fixed', [], [], '','' }; ...
            {'Qt',[7, 7],'double', -1,'real','Sample', 'Fixed', [], [], '','' }; ...
            {'Rt',[6, 6],'double', -1,'real','Sample', 'Fixed', [], [], '','' }; ...
            {'NavFlag',1,'double', -1,'real','Sample', 'Fixed', [], [], '','' }; ...
            }, ...
        };
        { ...
            'Bus_CON_density', ...
            {{'rho0',1,'double', -1,'real','Sample', 'Fixed', [], [], 'kg/m^3','Density at sea level' }; ...
            {'r0',1,'double', -1,'real','Sample', 'Fixed', [], [], 'km','Sea level position' }; ...
            {'H',1,'double', -1,'real','Sample', 'Fixed', [], [], 'km','Standardized height' }; ...
            }, ...
        };

};

Simulink.Bus.cellToObject(busCell);