%% Bus structure for constants


busCell = { ...
        { ...
            'Bus_outputs', ...
            {{'NXS_out',1,'Bus_state', -1,'real','Sample', 'Fixed', [], [], '','' }; ...
            {'astro_out',1,'Bus_state', -1,'real','Sample', 'Fixed', [], [], '','' }; ...
            }, ...
        };
        { ...
            'Bus_sat_norms', ...
            {{'NXS',1,'Bus_norms', -1,'real','Sample', 'Fixed', [], [], '','' }; ...
            {'astro',1,'Bus_norms', -1,'real','Sample', 'Fixed', [], [], '','' }; ...
            }, ...
        };
        { ...
            'Bus_norms', ...
            {{'r',1,'double', -1,'real','Sample', 'Fixed', [], [], 'km','Magnitude of the position' }; ...
            {'v',1,'double', -1,'real','Sample', 'Fixed', [], [], 'km/s','Magnitude of the velocity' }; ...
            }, ...
        };
        { ...
            'Bus_sat_oe', ...
            {{'NXS',1,'Bus_orbital_elems', -1,'real','Sample', 'Fixed', [], [], '','' }; ...
            {'astro',1,'Bus_orbital_elems', -1,'real','Sample', 'Fixed', [], [], '','' }; ...
            }, ...
        };
        { ...
            'Bus_orbital_elems', ...
            {{'a',1,'double', -1,'real','Sample', 'Fixed', [], [], 'km','Magnitude of the position' }; ...
            {'e',1,'double', -1,'real','Sample', 'Fixed', [], [], '','eccentricity' }; ...
            {'inc',1,'double', -1,'real','Sample', 'Fixed', [], [], 'deg','inclination' }; ...
            {'omega',1,'double', -1,'real','Sample', 'Fixed', [], [], 'deg','Ascending Node' }; ...
            {'w',1,'double', -1,'real','Sample', 'Fixed', [], [], 'deg','Argument of perigee' }; ...
            {'nu',1,'double', -1,'real','Sample', 'Fixed', [], [], 'deg','True anomaly' }; ...
            }, ...
        };
};

Simulink.Bus.cellToObject(busCell);