%% Bus structure for constants


busCell = { ...
        { ...
            'Bus_state', ...
            {{'r_i',3,'double', -1,'real','Sample', 'Fixed', [], [], 'km','Position in ECI' }; ...
            {'v_i',3,'double', -1,'real','Sample', 'Fixed', [], [], 'km/s','Velocity in ECI' }; ...
            {'q_b_i_b',4,'double', -1,'real','Sample', 'Fixed', [], [], '','Quaternion placeholder for now' }; ...
            }, ...
        };
        { ...
            'Bus_OE', ...
            {{'a',1,'double', -1,'real','Sample', 'Fixed', [], [], 'km','Semi-Major Axis' }; ...
            {'e',1,'double', -1,'real','Sample', 'Fixed', [], [], '','Eccentricity' }; ...
            {'inc',1,'double', -1,'real','Sample', 'Fixed', [], [], 'deg','Inclination' }; ...
            {'omega',1,'double', -1,'real','Sample', 'Fixed', [], [], 'deg','longitude of ascending node' }; ...
            {'w',1,'double', -1,'real','Sample', 'Fixed', [], [], 'deg','argument of perigee' }; ...
            {'nu',1,'double', -1,'real','Sample', 'Fixed', [], [], 'deg','true anomaly' }; ...
            }, ...
        };
};

Simulink.Bus.cellToObject(busCell);