%% Bus structure for constants


busCell = { ...
        { ...
            'Bus_CON', ...
            {{'mu',1,'double', -1,'real','Sample', 'Fixed', [], [], 'km^3/s^2','Gravitational Parameter for the Earth' }; ...
            {'gravityFlag',1,'double', -1,'real','Sample', 'Fixed', [], [], '','Gravity flag' }; ...
            {'Re',1,'double', -1,'real','Sample', 'Fixed', [], [], 'km','Radius of the Earth' }; ...
            {'J2',1,'double', -1,'real','Sample', 'Fixed', [], [], 'km^5/s^2','J2 Value' }; ...
            {'dragFlag',1,'double', -1,'real','Sample', 'Fixed', [], [], '','Drag flag' }; ...
            {'density',1,'Bus_CON_density', -1,'real','Sample', 'Fixed', [], [], '','Density Bus' }; ...
            }, ...
        };
        { ...
            'Bus_CON_density', ...
            {{'rho0',1,'double', -1,'real','Sample', 'Fixed', [], [], 'kg/m^3','Density at sea level' }; ...
            {'r0',1,'double', -1,'real','Sample', 'Fixed', [], [], 'km','Sea level position' }; ...
            {'H',1,'double', -1,'real','Sample', 'Fixed', [], [], 'km','Standardized height' }; ...
            }, ...
        };

};

Simulink.Bus.cellToObject(busCell);